<?php

/**
 * @file
 * Helper module for token tests.
 */

/**
 * Implements hook_exit().
 */
function token_test_exit() {
  if ($debug = \Drupal::state()->get('token_page_tokens', array())) {
    $debug += array('tokens' => array(), 'data' => array(), 'options' => array());
    foreach (array_keys($debug['tokens']) as $token) {
      $debug['values'][$token] = \Drupal::token()->replace($token, $debug['data'], $debug['options']);
    }
    \Drupal::state()->set('token_page_tokens', $debug);
  }
}

/**
 * Implements hook_date_format_types().
 *
 * @todo Remove when http://drupal.org/node/1173706 is fixed.
 */
function token_test_date_format_types() {
  $info['token_test'] = t('Token test date format');

  // Explicitly set the variable here as well.
  \Drupal::state()->set('date_format_token_test', 'Y');

  return $info;
}
