<?php

/**
 * @file
 * Helper module for token tests.
 */

/**
 * Implements hook_page_alter().
 */
function token_test_page_alter() {
  if ($debug = \Drupal::state()->get('token_page_tokens', array())) {
    $debug += array('tokens' => array(), 'data' => array(), 'options' => array());
    foreach (array_keys($debug['tokens']) as $token) {
      $debug['values'][$token] = \Drupal::token()->replace($token, $debug['data'], $debug['options']);
    }
    \Drupal::state()->set('token_page_tokens', $debug);
  }
}
